export const GRIDDLE_ROW_SELECTION_TOGGLED = 'GRIDDLE_ROW_SELECTION_TOGGLED';
export const GRIDDLE_START_LOADING = 'GRIDDLE_START_LOADING';
export const GRIDDLE_REMOTE_REPLACE_DATA = 'GRIDDLE_REMOTE_REPLACE_DATA';
export const GRIDDLE_REMOTE_APPEND_DATA = 'GRIDDLE_REMOTE_APPEND_DATA';
export const GRIDDLE_REMOTE_PREPEND_DATA = 'GRIDDLE_REMOTE_PREPEND_DATA';
export const GRIDDLE_REMOTE_ERROR = 'GRIDDLE_REMOTE_ERROR';